### PR TITLE
Fixing deprecations, and removing old version locks on gems

### PR DESCRIPTION
**Pull request by allavena**
There are some old gems being required here. such as Hashie v. 1.2.

### CODE REVIEW

**Comment by Gazler** [comment]
Hey - thanks for the pull request.

I don't think we should remove version numbers entirely, so I propose the following:

 * Reference the latest versions of the gems in use
 * Remove Ruby 1.8.7, 1.9.2 and jruby-1.8 from `.travis.yml`
 * Add Ruby 2.1.0 and 2.2.0 to `travis.yml`
 * Update the README to state that for Ruby 1.9.2 and below to use the `0.3` version of the gem
 * Change the code block at https://github.com/allavena/rapidash/blob/master/rapidash.gemspec#L21L26 to only include one version since there is no need to support 1.9.2 and below
* Add the latest versions of the gems to the dependencies instead of removing the version number entirely

Let me know how that sounds. If you don't have time to do it then I can do it and release it as `0.4.0`

Thanks.

**Comment by allavena** [comment]
Hi Gary,

Give me a few days and I'll update the pull request.

I don't know best practices for fixing dependencies, so I'll go with,
keeping the gems on which you had specified a dependency (just with a
more recent version), and the ones that are not version locked will stay
that way.

There are two things that have warnings / obsolete. I already fixed one,
left is some rspec syntax.

André


Gary Rennie wrote on 20/07/15 19:55:
>
> Hey - thanks for the pull request.
>
> I don't think we should remove version numbers entirely, so I propose
> the following:
>
>   * Reference the latest versions of the gems in use
>   * Remove Ruby 1.8.7, 1.9.2 and jruby-1.8 from |.travis.yml|
>   * Add Ruby 2.1.0 and 2.2.0 to |travis.yml|
>   * Update the README to state that for Ruby 1.9.2 and below to use
>     the |0.3| version of the gem
>   * Change the code block at
>     https://github.com/allavena/rapidash/blob/master/rapidash.gemspec#L21L26
>     to only include one version since there is no need to support
>     1.9.2 and below
>       o Add the latest versions of the gems to the dependencies
>         instead of removing the version number entirely
>
> Let me know how that sounds. If you don't have time to do it then I
> can do it and release it as |0.4.0|
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gazler/rapidash/pull/23#issuecomment-122829822>.
>


-- 
André Allavena, PhD
CTO
Interactive Gaming Entertainment Pty Ltd

Suite 22, 20 Park Rd 
Milton Qld 4064

**Comment by Gazler** [comment]
Hi André,

That sounds like a decent way to handle the versions for the dependencies.
I am happy to update to use RSpec 3 if that is what you mean.

Look forward to your updates.

Thanks,
Gary

**Comment by allavena** [comment]
All done.

Updated Travis, bumped RSPec up to 3 and updated syntax.

Enlarged the range of some dependencies.


> bundle outdated
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...

Bundle up to date!


Good to merge I think.



Gary Rennie wrote on 21/07/15 17:56:
>
> Hi André,
>
> That sounds like a decent way to handle the versions for the dependencies.
> I am happy to update to use RSpec 3 if that is what you mean.
>
> Look forward to your updates.
>
> Thanks,
> Gary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gazler/rapidash/pull/23#issuecomment-123205089>.
>


-- 
André Allavena, PhD
CTO
Interactive Gaming Entertainment Pty Ltd

Suite 22, 20 Park Rd 
Milton Qld 4064

**Pull request merged**
